inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - utils:unsafe
  - duplicated

ignore-paths:
  - applications_download/configuration.py
  - applications_download/applications_definition.py
